language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - TEST_DIR=subnet_cruncher

script:
  - cd $TEST_DIR && pip install -r dev-requirements.txt && "PYTHONPATH=. py.test --cov=subnet_cruncher tests"
