language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - TEST_DIR=subnet_cruncher

install:
  - pip install -r dev-requirements.txt

script:
  - pwd
  - cd subnet_cruncher && make test
